name: flutter_web
description: A flutter web app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  emojis: ^0.9.3
  simple_animations: ^3.0.0
  supercharged: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Zen Dots
      fonts:
        - asset: fonts/ZenDots-Regular.ttf
          #weight: 400
